package com.ly.mt.activity.server.product.mapper;

import com.ly.mt.core.common.entity.hd.HdGoodsSkuInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface HdGoodsSkuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku_info
     *
     * @mbggenerated
     */
    int insert(HdGoodsSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku_info
     *
     * @mbggenerated
     */
    int insertSelective(HdGoodsSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku_info
     *
     * @mbggenerated
     */
    HdGoodsSkuInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HdGoodsSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HdGoodsSkuInfo record);
}