package com.ly.mt.activity.server.product.mapper;

import com.ly.mt.core.common.entity.hd.HdGoodsSpuInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface HdGoodsSpuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spu_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spu_info
     *
     * @mbggenerated
     */
    int insert(HdGoodsSpuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spu_info
     *
     * @mbggenerated
     */
    int insertSelective(HdGoodsSpuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spu_info
     *
     * @mbggenerated
     */
    HdGoodsSpuInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spu_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HdGoodsSpuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spu_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HdGoodsSpuInfo record);
}