package com.ly.mt.core.base.dict;

/**
 * @Description Snowflake主键id生成配置枚举
 * @Author taoye
 */
public enum PrimaryKey {
    PRIMARY_KEY_RANDOM(0, 0),

    PRIMARY_KEY_ACTIVITY_GOODS_DETAIL(1, 1),
    PRIMARY_KEY_ACTIVITY_INFO(1, 2),
    PRIMARY_KEY_ACTIVITY_SIGN_UP_CABINET(1, 3),
    PRIMARY_KEY_ACTIVITY_USER_GRADE(1, 4),
    PRIMARY_KEY_ACTIVITY_USER_GRADE_DETAIL(1, 5),

    PRIMARY_KEY_BASIC_AREA(2, 1),
    PRIMARY_KEY_BASIC_FUNC(2, 2),
    PRIMARY_KEY_BASIC_ROLE(2, 3),
    PRIMARY_KEY_BASIC_ROLE_RIGHT(2, 4),
    PRIMARY_KEY_BASIC_USER_ROLE(2, 5),

    PRIMARY_KEY_BLUETOOTH_CALENDAR(3, 1),
    PRIMARY_KEY_BLUETOOTH_FIRMWARE_SETTING(3, 2),
    PRIMARY_KEY_BLUETOOTH_INDEX(3, 3),
    PRIMARY_KEY_BLUETOOTH_INDEX_LOG(3, 4),
    PRIMARY_KEY_BLUETOOTH_LOG(3, 5),
    PRIMARY_KEY_BLUETOOTH_TASTE_BEST(3, 6),
    PRIMARY_KEY_BLUETOOTH_TASTE_INFO(3, 7),
    PRIMARY_KEY_BLUETOOTH_USER_BIND(3, 8),
    PRIMARY_KEY_BLUETOOTH_USER_SUBSIDIARY(3, 9),
    PRIMARY_KEY_BLUETOOTH_USER_SUGGESTIONS(3, 10),
    PRIMARY_KEY_BLUETOOTH_USER_TASTE(3, 11),
    PRIMARY_KEY_BLUETOOTH_COLLECT(3, 12),

    PRIMARY_KEY_CITY_ONE_HOUR(4, 1),

    PRIMARY_KEY_COUPON_CODE(4, 2),
    PRIMARY_KEY_COUPON_GOODS(4, 3),
    PRIMARY_KEY_COUPON_INFO(4, 4),

    PRIMARY_KEY_GOODS_ATTR(5, 1),
    PRIMARY_KEY_GOODS_ATTR_VALUE(5, 2),
    PRIMARY_KEY_GOODS_BRAND_INFO(5, 3),
    PRIMARY_KEY_GOODS_CATEGROY_INFO(5, 4),
    PRIMARY_KEY_GOODS_HOUR_SKU(5, 5),
    PRIMARY_KEY_GOODS_SKU_CODE(5, 6),
    PRIMARY_KEY_GOODS_SKU_CODE_IMPORT_RECORD(5, 7),
    PRIMARY_KEY_GOODS_SKU_INFO(5, 8),
    PRIMARY_KEY_GOODS_SKU_INFO_TEMP(5, 9),
    PRIMARY_KEY_GOODS_SKU_PICTURE(5, 10),
    PRIMARY_KEY_GOODS_SKU_PRICE(5, 11),
    PRIMARY_KEY_GOODS_SPU_ATTR(5, 12),
    PRIMARY_KEY_GOODS_SPU_ATTR_VALUE(5, 13),
    PRIMARY_KEY_GOODS_SPU_INFO(5, 14),
    PRIMARY_KEY_GOODS_SPU_INFO_TEMP(5, 15),
    PRIMARY_KEY_GOODS_SPU_PICTURE(5, 16),

    PRIMARY_KEY_GY_SHOP_INFO(6, 1),

    PRIMARY_KEY_GZG_B_USER(7, 1),
    PRIMARY_KEY_GZG_B_USER_RELATION(7, 2),
    PRIMARY_KEY_GZG_BANNER_PICTURE(7, 3),
    PRIMARY_KEY_GZG_CABINET(7, 4),
    PRIMARY_KEY_GZG_CHANNEL_CODE(7, 5),
    PRIMARY_KEY_GZG_CITY(7, 6),
    PRIMARY_KEY_GZG_COUPON_CODE(7, 7),
    PRIMARY_KEY_GZG_COUPON_GOODS(7, 8),
    PRIMARY_KEY_GZG_COUPON_INFO(7, 9),
    PRIMARY_KEY_GZG_DEVICE_CHECK_LOG(7, 10),
    PRIMARY_KEY_GZG_GOODS_PLAN(7, 11),
    PRIMARY_KEY_GZG_HOTEL(7, 12),
    PRIMARY_KEY_GZG_HOTEL_STOCK(7, 13),
    PRIMARY_KEY_GZG_HOTEL_USER_RELATION(7, 14),
    PRIMARY_KEY_GZG_INFO(7, 15),
    PRIMARY_KEY_GZG_ONLINE_LOG(7, 16),
    PRIMARY_KEY_GZG_ORDER_ITEMS(7, 17),
    PRIMARY_KEY_GZG_ORDER_PAY(7, 18),
    PRIMARY_KEY_GZG_ORDER(7, 19),
    PRIMARY_KEY_GZG_PLAN(7, 20),
    PRIMARY_KEY_GZG_REPLENISH_ORDER(7, 21),
    PRIMARY_KEY_GZG_REPLENISH_RECORD(7, 22),
    PRIMARY_KEY_GZG_SKU_PICTURE(7, 23),
    PRIMARY_KEY_GZG_STORE_INFO(7, 24),
    PRIMARY_KEY_GZG_PROGRAMME(7, 25),
    PRIMARY_KEY_GZG_REPLENISH(7, 26),
    PRIMARY_KEY_CABINET_INFO(7, 26),
    PRIMARY_KEY_CABINET_CREATE_RECORD(7, 27),
    PRIMARY_KEY_CABINET_STORE_PROFIT(7, 28),
    PRIMARY_KEY_CABINET_STORE_PROFIT_LOG(7, 29),
    PRIMARY_KEY_CABINET_MESSAGE(7, 30),
    PRIMARY_KEY_CABINET_CATEGROY(7, 31),


    PRIMARY_KEY_HD_ACTIVITY_USER(8, 1),
    PRIMARY_KEY_HD_OPERATOR_INFO(8, 2),
    PRIMARY_KEY_HD_SHOP_ATT_DETAIL(8, 3),
    PRIMARY_KEY_HD_SHOP_ATT_GOODS_SPU(8, 4),
    PRIMARY_KEY_HD_SHOP_ATT_ORDER(8, 5),
    PRIMARY_KEY_HD_SHOP_ATT_ORDER_DETAIL(8, 6),

    PRIMARY_KEY_LOAD_RUNNER_PERSONNELS(9, 1),

    PRIMARY_KEY_LODE_RUNNER_CLUES(10, 1),
    PRIMARY_KEY_LODE_RUNNER_CODES(10, 2),
    PRIMARY_KEY_LODE_RUNNER_CONFIGS(10, 3),
    PRIMARY_KEY_LODE_RUNNER_TREES(10, 4),
    PRIMARY_KEY_LODE_RUNNER_USER_CODES(10, 5),
    PRIMARY_KEY_LODE_RUNNER_USER_CONFIGS(10, 6),
    PRIMARY_KEY_LODE_RUNNER_USER_TREES(10, 7),

    PRIMARY_KEY_NOTICE_LOGS(11, 1),

    PRIMARY_KEY_ORDER_BATTLE_CHECK_LOGS(12, 1),
    PRIMARY_KEY_ORDER_BATTLE_EXPRESSES(12, 2),
    PRIMARY_KEY_ORDER_BATTLE_LOGS(12, 3),
    PRIMARY_KEY_ORDER_BATTLE_SHOP(12, 4),
    PRIMARY_KEY_ORDERS_BATTLE_INFO(12, 5),

    PRIMARY_KEY_PAYMENT_DETAIL(13, 1),

    PRIMARY_KEY_PLATFORM_LOGISTICS(14, 1),

    PRIMARY_KEY_POINT_CONFIG(15, 1),
    PRIMARY_KEY_POINT_GRADE(15, 2),
    PRIMARY_KEY_POINT_MALL_RULE(15, 3),
    PRIMARY_KEY_POINT_MALL_RULE_DETAIL(15, 4),

    PRIMARY_KEY_PUNCH_CARD_COUPON(16, 1),
    PRIMARY_KEY_PUNCH_CARD_POINT(16, 2),

    PRIMARY_KEY_ROTATION_INFO(17, 1),

    PRIMARY_KEY_SHARE_GOODS(18, 1),
    PRIMARY_KEY_SHARE_GOODS_PICTURE_DEL(18, 2),

    PRIMARY_KEY_SHOP_ADDRESS(19, 1),
    PRIMARY_KEY_SHOP_COUPON(19, 2),
    PRIMARY_KEY_SHOP_GRAB_BLACK_LIST(19, 3),
    PRIMARY_KEY_SHOP_GRADE(19, 4),
    PRIMARY_KEY_SHOP_INFO(19, 5),
    PRIMARY_KEY_SHOP_LICENSES(19, 6),
    PRIMARY_KEY_SHOP_PROFIT_LOGS(19, 7),
    PRIMARY_KEY_SHOP_PROFITS(19, 8),
    PRIMARY_KEY_SHOP_PURACHASES_LADDER_PRICE(19, 9),
    PRIMARY_KEY_SHOP_PURCHASES(19, 10),
    PRIMARY_KEY_SHOP_PURCHASES_DISCOUNT(19, 11),
    PRIMARY_KEY_SHOP_PURCHASES_ITEMS(19, 12),
    PRIMARY_KEY_SHOP_PURCHASES_REFUND(19, 13),
    PRIMARY_KEY_SHOP_PURCHASES_REFUND_ITEM(19, 14),
    PRIMARY_KEY_SHOP_REFUND_IMAGES(19, 15),
    PRIMARY_KEY_SHOP_SHARE_LOG(19, 16),
    PRIMARY_KEY_SHOP_STOCKS(19, 17),

    PRIMARY_KEY_TRADE_DISTRIBUTION_MODE(20, 1),
    PRIMARY_KEY_TRADE_INVOICE(20, 2),
    PRIMARY_KEY_TRADE_ORDER_COUPON(20, 3),
    PRIMARY_KEY_TRADE_ORDER_ITEMS(20, 4),
    PRIMARY_KEY_TRADE_ORDER_MEDIA(20, 5),
    PRIMARY_KEY_TRADE_ORDER_MQ_LOG(20, 6),
    PRIMARY_KEY_TRADE_ORDER_REFUND(20, 7),
    PRIMARY_KEY_TRADE_ORDER_REFUND_ITEM(20, 8),
    PRIMARY_KEY_TRADE_ORDER_VIE(20, 9),
    PRIMARY_KEY_TRADE_ORDERS(20, 10),

    PRIMARY_KEY_USER(21, 1),
    PRIMARY_KEY_USER_ADDRESS(21, 2),
    PRIMARY_KEY_USER_BINDS(21, 3),
    PRIMARY_KEY_USER_CONNECTIONS(21, 4),
    PRIMARY_KEY_USER_COUPONE_CODE_DEL(21, 5),
    PRIMARY_KEY_USER_FEEDBACK(21, 6),
    PRIMARY_KEY_USER_FEEDBACK_IMAGES(21, 7),
    PRIMARY_KEY_USER_FRIENDS(21, 8),
    PRIMARY_KEY_USER_MAKE_MONEY(21, 9),
    PRIMARY_KEY_USER_MAKE_MONEY_MONTHS(21, 10),
    PRIMARY_KEY_USER_NOTICES(21, 11),
    PRIMARY_KEY_USER_POINT_DATA(21, 12),
    PRIMARY_KEY_USER_POINT_GRADE(21, 13),
    PRIMARY_KEY_USER_PROFIT_LOGS(21, 14),
    PRIMARY_KEY_USER_PROFITS(21, 15),
    PRIMARY_KEY_USER_PUNCH_CARD(21, 16),
    PRIMARY_KEY_USER_REALS(21, 17),
    PRIMARY_KEY_USER_TASK(21, 18),
    PRIMARY_KEY_USER_TASK_FINISHED(21, 19),
    PRIMARY_KEY_USER_UPDATE_LOGIN_NAME_LOGS(21, 20),
    PRIMARY_KEY_USER_WALLET_LOGS(21, 21),
    PRIMARY_KEY_USER_WALLETS(21, 22),
    PRIMARY_KEY_USER_SHARE(21, 23),
    PRIMARY_KEY_USER_CERTIFICATION(21, 24),


    PRIMARY_KEY_VOTE_CITY(22, 1),
    PRIMARY_KEY_VOTE_CONFIG(22, 2),

    PRIMARY_KEY_WAREHOUSE_INFO(23, 1),

    //微信shop店铺
    PRIMARY_KEY_WX_SHOP(24, 1),
    PRIMARY_KEY_CASH_RECORD(26, 1),
    PRIMARY_KEY_REWARD_RECORD(27, 1),
    PRIMARY_KEY_REPLENISH_REWARD(28, 1),


    /**
     * @Description 以下为待确定无用后删除的枚举，添加新枚举请在上方添加
     * @Author taoye
     */
    PRIMARY_KEY_ORDER_NO(1, 4),
    PRIMARY_KEY_ORDERS_BATTLE_SHOP(1, 9),
    PRIMARY_KEY_ORDERS_BATTLE_LOGS(1, 10),
    PRIMARY_KEY_PAYMENT_DEAL(4, 2),
    PRIMARY_KEY_GZG_HOTEL_INFO(6, 1),
    PRIMARY_KEY_GZG_RUJIN_RELATION(6, 3),


    PRIMARY_KEY_REPLENISH_ORDER(5, 1),
    PRIMARY_KEY_REPLENISH_ORDER_RECORD(5, 2),
    PRIMARY_KEY_SHOP_USER(6, 1),
    PRIMARY_KEY_SHOP_USER_ADDRESS(6, 2),
    PRIMARY_KEY_SHOP_USER_LICENSES(6, 4),

    USER(1, 1),
    USER_ADDRESS(1, 2),
    USER_UPDATE_LOGIN_NAME_LOGS(1, 12),
    USER_FEEDBACK(1, 13),
    USER_FEEDBACK_IMAGES(1, 14),
    TRADE_ORDERS(1, 3),
    ORDER_NO(1, 4),
    TRADE_ORDER_ITEMS(1, 5),
    TRADE_ORDER_COUPON(1, 6),
    ORDERS_BATTLE_INFO(1, 7),
    ORDERS_BATTLE_SHOP(1, 8),
    ORDERS_BATTLE_LOGS(1, 9),
    ORDER_BATTLE_CHECK_LOGS(1, 10),
    ORDER_BATTLE_EXPRESSES(1, 11),
    GOODS_SPU_INFO(2, 1),
    COUPON_CODE(2, 2),
    COUPON_INFO(2, 3),
    ROTATION_INFO(2, 4),
    GOODS_SKU_PICTURE(2, 5),
    POINT_GRADE(3, 2),
    USER_POINT_DATA(3, 1),
    USER_POINT_GRADE(3, 3),
    USER_PUNCH_CARD(3, 4),
    PAYMENT_DETAIL(4, 1),
    PAYMENT_DEAL(4, 2),
    ACTIVITY_USER_GRADE_DETAIL(5, 1),
    GZG_HOTEL_INFO(6, 1),
    GZG_INFO(6, 2),
    REPLENISH_ORDER(5, 1),
    REPLENISH_ORDER_RECORD(5, 2),
    SHOP_USER(6, 1),
    SHOP_USER_ADDRESS(6, 2),
    LODE_RUNNER_TREES(6, 3),
    SHOP_USER_LICENSES(6, 4),
    SHOP_PROFIT_LOGS(6, 5),
    SHOP_PROFITS(6, 6),
    SHOP_ADDRESS(6, 7),
    HD_ACTIVITY_USER(7, 1),
    HD_OPERATOR_INFO(7, 2),
    HD_SHOP_ATT_DETAIL(7, 3),
    HD_SHOP_ATT_GOODS_SPU(7, 4),
    HD_SHOP_ATT_ORDER(7, 5),
    HD_SHOP_ATT_ORDER_DETAIL(7, 6),
    HD_PARTNER(7, 7),

    ORDER_REFUND_ID(8, 1),
    ORDER_REFUND_ITEM_ID(8, 2),
    VOTE_CITY_ID(9, 1);


    private final long workerId;
    private final long datacenterId;

    PrimaryKey(long workerId, long datacenterId) {
        this.workerId = workerId;
        this.datacenterId = datacenterId;
    }

    public long getWorkerId() {
        return workerId;
    }

    public long getDatacenterId() {
        return datacenterId;
    }
}