package com.ly.mt.core.common.entity.hd;

import java.io.Serializable;
import java.util.Date;

public class HdActivityInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.denomination
     *
     * @mbggenerated
     */
    private Double denomination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.discount_rate
     *
     * @mbggenerated
     */
    private Double discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.coupon_activity_type
     *
     * @mbggenerated
     */
    private String couponActivityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.use_channel
     *
     * @mbggenerated
     */
    private String useChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.start_fee
     *
     * @mbggenerated
     */
    private Double startFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.max_sell_num
     *
     * @mbggenerated
     */
    private Integer maxSellNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.goods_limit_category
     *
     * @mbggenerated
     */
    private Integer goodsLimitCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.id
     *
     * @return the value of activity_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.id
     *
     * @param id the value for activity_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.name
     *
     * @return the value of activity_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.name
     *
     * @param name the value for activity_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.start_time
     *
     * @return the value of activity_info.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.start_time
     *
     * @param startTime the value for activity_info.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.end_time
     *
     * @return the value of activity_info.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.end_time
     *
     * @param endTime the value for activity_info.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.denomination
     *
     * @return the value of activity_info.denomination
     *
     * @mbggenerated
     */
    public Double getDenomination() {
        return denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.denomination
     *
     * @param denomination the value for activity_info.denomination
     *
     * @mbggenerated
     */
    public void setDenomination(Double denomination) {
        this.denomination = denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.discount_rate
     *
     * @return the value of activity_info.discount_rate
     *
     * @mbggenerated
     */
    public Double getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.discount_rate
     *
     * @param discountRate the value for activity_info.discount_rate
     *
     * @mbggenerated
     */
    public void setDiscountRate(Double discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.coupon_activity_type
     *
     * @return the value of activity_info.coupon_activity_type
     *
     * @mbggenerated
     */
    public String getCouponActivityType() {
        return couponActivityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.coupon_activity_type
     *
     * @param couponActivityType the value for activity_info.coupon_activity_type
     *
     * @mbggenerated
     */
    public void setCouponActivityType(String couponActivityType) {
        this.couponActivityType = couponActivityType == null ? null : couponActivityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.use_channel
     *
     * @return the value of activity_info.use_channel
     *
     * @mbggenerated
     */
    public String getUseChannel() {
        return useChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.use_channel
     *
     * @param useChannel the value for activity_info.use_channel
     *
     * @mbggenerated
     */
    public void setUseChannel(String useChannel) {
        this.useChannel = useChannel == null ? null : useChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.source
     *
     * @return the value of activity_info.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.source
     *
     * @param source the value for activity_info.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.start_fee
     *
     * @return the value of activity_info.start_fee
     *
     * @mbggenerated
     */
    public Double getStartFee() {
        return startFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.start_fee
     *
     * @param startFee the value for activity_info.start_fee
     *
     * @mbggenerated
     */
    public void setStartFee(Double startFee) {
        this.startFee = startFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.max_sell_num
     *
     * @return the value of activity_info.max_sell_num
     *
     * @mbggenerated
     */
    public Integer getMaxSellNum() {
        return maxSellNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.max_sell_num
     *
     * @param maxSellNum the value for activity_info.max_sell_num
     *
     * @mbggenerated
     */
    public void setMaxSellNum(Integer maxSellNum) {
        this.maxSellNum = maxSellNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.goods_limit_category
     *
     * @return the value of activity_info.goods_limit_category
     *
     * @mbggenerated
     */
    public Integer getGoodsLimitCategory() {
        return goodsLimitCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.goods_limit_category
     *
     * @param goodsLimitCategory the value for activity_info.goods_limit_category
     *
     * @mbggenerated
     */
    public void setGoodsLimitCategory(Integer goodsLimitCategory) {
        this.goodsLimitCategory = goodsLimitCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.status
     *
     * @return the value of activity_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.status
     *
     * @param status the value for activity_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.description
     *
     * @return the value of activity_info.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.description
     *
     * @param description the value for activity_info.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.creator
     *
     * @return the value of activity_info.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.creator
     *
     * @param creator the value for activity_info.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.create_time
     *
     * @return the value of activity_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.create_time
     *
     * @param createTime the value for activity_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", denomination=").append(denomination);
        sb.append(", discountRate=").append(discountRate);
        sb.append(", couponActivityType=").append(couponActivityType);
        sb.append(", useChannel=").append(useChannel);
        sb.append(", source=").append(source);
        sb.append(", startFee=").append(startFee);
        sb.append(", maxSellNum=").append(maxSellNum);
        sb.append(", goodsLimitCategory=").append(goodsLimitCategory);
        sb.append(", status=").append(status);
        sb.append(", description=").append(description);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}