package com.ly.mt.core.common.entity.hd;

import java.io.Serializable;
import java.util.Date;

public class HdGoodsSpuInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.name_gy
     *
     * @mbggenerated
     */
    private String nameGy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.cid
     *
     * @mbggenerated
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.brand_id
     *
     * @mbggenerated
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.market_price
     *
     * @mbggenerated
     */
    private Double marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.wholesale_price
     *
     * @mbggenerated
     */
    private Double wholesalePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.weight
     *
     * @mbggenerated
     */
    private Long weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.picture_url
     *
     * @mbggenerated
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.describe_url
     *
     * @mbggenerated
     */
    private String describeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.spu_attr
     *
     * @mbggenerated
     */
    private String spuAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.spu_status
     *
     * @mbggenerated
     */
    private Integer spuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.data_source
     *
     * @mbggenerated
     */
    private Integer dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_spu_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.id
     *
     * @return the value of goods_spu_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.id
     *
     * @param id the value for goods_spu_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.name_gy
     *
     * @return the value of goods_spu_info.name_gy
     *
     * @mbggenerated
     */
    public String getNameGy() {
        return nameGy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.name_gy
     *
     * @param nameGy the value for goods_spu_info.name_gy
     *
     * @mbggenerated
     */
    public void setNameGy(String nameGy) {
        this.nameGy = nameGy == null ? null : nameGy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.name
     *
     * @return the value of goods_spu_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.name
     *
     * @param name the value for goods_spu_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.code
     *
     * @return the value of goods_spu_info.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.code
     *
     * @param code the value for goods_spu_info.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.cid
     *
     * @return the value of goods_spu_info.cid
     *
     * @mbggenerated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.cid
     *
     * @param cid the value for goods_spu_info.cid
     *
     * @mbggenerated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.brand_id
     *
     * @return the value of goods_spu_info.brand_id
     *
     * @mbggenerated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.brand_id
     *
     * @param brandId the value for goods_spu_info.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.market_price
     *
     * @return the value of goods_spu_info.market_price
     *
     * @mbggenerated
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.market_price
     *
     * @param marketPrice the value for goods_spu_info.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.wholesale_price
     *
     * @return the value of goods_spu_info.wholesale_price
     *
     * @mbggenerated
     */
    public Double getWholesalePrice() {
        return wholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.wholesale_price
     *
     * @param wholesalePrice the value for goods_spu_info.wholesale_price
     *
     * @mbggenerated
     */
    public void setWholesalePrice(Double wholesalePrice) {
        this.wholesalePrice = wholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.weight
     *
     * @return the value of goods_spu_info.weight
     *
     * @mbggenerated
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.weight
     *
     * @param weight the value for goods_spu_info.weight
     *
     * @mbggenerated
     */
    public void setWeight(Long weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.picture_url
     *
     * @return the value of goods_spu_info.picture_url
     *
     * @mbggenerated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.picture_url
     *
     * @param pictureUrl the value for goods_spu_info.picture_url
     *
     * @mbggenerated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.describe_url
     *
     * @return the value of goods_spu_info.describe_url
     *
     * @mbggenerated
     */
    public String getDescribeUrl() {
        return describeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.describe_url
     *
     * @param describeUrl the value for goods_spu_info.describe_url
     *
     * @mbggenerated
     */
    public void setDescribeUrl(String describeUrl) {
        this.describeUrl = describeUrl == null ? null : describeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.spu_attr
     *
     * @return the value of goods_spu_info.spu_attr
     *
     * @mbggenerated
     */
    public String getSpuAttr() {
        return spuAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.spu_attr
     *
     * @param spuAttr the value for goods_spu_info.spu_attr
     *
     * @mbggenerated
     */
    public void setSpuAttr(String spuAttr) {
        this.spuAttr = spuAttr == null ? null : spuAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.spu_status
     *
     * @return the value of goods_spu_info.spu_status
     *
     * @mbggenerated
     */
    public Integer getSpuStatus() {
        return spuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.spu_status
     *
     * @param spuStatus the value for goods_spu_info.spu_status
     *
     * @mbggenerated
     */
    public void setSpuStatus(Integer spuStatus) {
        this.spuStatus = spuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.data_source
     *
     * @return the value of goods_spu_info.data_source
     *
     * @mbggenerated
     */
    public Integer getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.data_source
     *
     * @param dataSource the value for goods_spu_info.data_source
     *
     * @mbggenerated
     */
    public void setDataSource(Integer dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.create_time
     *
     * @return the value of goods_spu_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.create_time
     *
     * @param createTime the value for goods_spu_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.modify_time
     *
     * @return the value of goods_spu_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.modify_time
     *
     * @param modifyTime the value for goods_spu_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu_info.remark
     *
     * @return the value of goods_spu_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu_info.remark
     *
     * @param remark the value for goods_spu_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spu_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", nameGy=").append(nameGy);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", cid=").append(cid);
        sb.append(", brandId=").append(brandId);
        sb.append(", marketPrice=").append(marketPrice);
        sb.append(", wholesalePrice=").append(wholesalePrice);
        sb.append(", weight=").append(weight);
        sb.append(", pictureUrl=").append(pictureUrl);
        sb.append(", describeUrl=").append(describeUrl);
        sb.append(", spuAttr=").append(spuAttr);
        sb.append(", spuStatus=").append(spuStatus);
        sb.append(", dataSource=").append(dataSource);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}