package com.ly.mt.core.common.entity.hd;

import java.io.Serializable;
import java.util.Date;

public class HdShopAttDetail implements Serializable {

    public HdShopAttDetail() {
    }

    /**
     * 自增主键
     * @mbggenerated
     */
    private Long id;

    /**
     * 门店主键id
     * @mbggenerated
     */
    private Long shopId;

    /**
     * 活动主键id
     * @mbggenerated
     */
    private Long activityId;

    /**
     *
     * 活动二维码
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * 活动负责人
     * @mbggenerated
     */
    private String activityManager;

    /**
     * 活动负责人手机号（作为活动登录账号使用）
     * @mbggenerated
     */
    private String managerPhone;

    /**
     * 门店活动有效性(0失效、1有效)
     * @mbggenerated
     */
    private String shopAttStatus;

    /**
     * 入库时间
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 更新时间
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 限制用户参与的次数，0为不限制
     */
    private Integer userJoinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hd_shop_att_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public Integer getUserJoinNum() {
        return userJoinNum;
    }

    public void setUserJoinNum(Integer userJoinNum) {
        this.userJoinNum = userJoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.id
     *
     * @return the value of hd_shop_att_detail.id
     *
     * @mbggenerated
     */



    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.id
     *
     * @param id the value for hd_shop_att_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.shop_id
     *
     * @return the value of hd_shop_att_detail.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.shop_id
     *
     * @param shopId the value for hd_shop_att_detail.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.activity_id
     *
     * @return the value of hd_shop_att_detail.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.activity_id
     *
     * @param activityId the value for hd_shop_att_detail.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.image_url
     *
     * @return the value of hd_shop_att_detail.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.image_url
     *
     * @param imageUrl the value for hd_shop_att_detail.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.activity_manager
     *
     * @return the value of hd_shop_att_detail.activity_manager
     *
     * @mbggenerated
     */
    public String getActivityManager() {
        return activityManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.activity_manager
     *
     * @param activityManager the value for hd_shop_att_detail.activity_manager
     *
     * @mbggenerated
     */
    public void setActivityManager(String activityManager) {
        this.activityManager = activityManager == null ? null : activityManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.manager_phone
     *
     * @return the value of hd_shop_att_detail.manager_phone
     *
     * @mbggenerated
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.manager_phone
     *
     * @param managerPhone the value for hd_shop_att_detail.manager_phone
     *
     * @mbggenerated
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.shop_att_status
     *
     * @return the value of hd_shop_att_detail.shop_att_status
     *
     * @mbggenerated
     */
    public String getShopAttStatus() {
        return shopAttStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.shop_att_status
     *
     * @param shopAttStatus the value for hd_shop_att_detail.shop_att_status
     *
     * @mbggenerated
     */
    public void setShopAttStatus(String shopAttStatus) {
        this.shopAttStatus = shopAttStatus == null ? null : shopAttStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.create_time
     *
     * @return the value of hd_shop_att_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.create_time
     *
     * @param createTime the value for hd_shop_att_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_detail.update_time
     *
     * @return the value of hd_shop_att_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_detail.update_time
     *
     * @param updateTime the value for hd_shop_att_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shopId=").append(shopId);
        sb.append(", activityId=").append(activityId);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", activityManager=").append(activityManager);
        sb.append(", managerPhone=").append(managerPhone);
        sb.append(", shopAttStatus=").append(shopAttStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}