package com.ly.mt.core.common.entity.hd;

import java.io.Serializable;
import java.util.Date;

public class HdShopInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.send_lon
     *
     * @mbggenerated
     */
    private String sendLon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.send_lat
     *
     * @mbggenerated
     */
    private String sendLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.send_address
     *
     * @mbggenerated
     */
    private String sendAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.send_country
     *
     * @mbggenerated
     */
    private String sendCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.send_province_code
     *
     * @mbggenerated
     */
    private String sendProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.send_city_code
     *
     * @mbggenerated
     */
    private String sendCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_type
     *
     * @mbggenerated
     */
    private Byte shopType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_lon
     *
     * @mbggenerated
     */
    private String shopLon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_lat
     *
     * @mbggenerated
     */
    private String shopLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_address
     *
     * @mbggenerated
     */
    private String shopAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_country
     *
     * @mbggenerated
     */
    private String shopCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_province_code
     *
     * @mbggenerated
     */
    private String shopProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_city_code
     *
     * @mbggenerated
     */
    private String shopCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.idcard_front
     *
     * @mbggenerated
     */
    private String idcardFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.idcard_back
     *
     * @mbggenerated
     */
    private String idcardBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.vaild_type
     *
     * @mbggenerated
     */
    private Byte vaildType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.vaild_start_at
     *
     * @mbggenerated
     */
    private Date vaildStartAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.vaild_end_at
     *
     * @mbggenerated
     */
    private Date vaildEndAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.invite_code
     *
     * @mbggenerated
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.vip
     *
     * @mbggenerated
     */
    private Byte vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.level
     *
     * @mbggenerated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.stock_num
     *
     * @mbggenerated
     */
    private Integer stockNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.create_time2
     *
     * @mbggenerated
     */
    private Date createTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.operator_id
     *
     * @mbggenerated
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.slogan
     *
     * @mbggenerated
     */
    private String slogan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.id
     *
     * @return the value of shop_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.id
     *
     * @param id the value for shop_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.user_id
     *
     * @return the value of shop_info.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.user_id
     *
     * @param userId the value for shop_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.mobile
     *
     * @return the value of shop_info.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.mobile
     *
     * @param mobile the value for shop_info.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.status
     *
     * @return the value of shop_info.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.status
     *
     * @param status the value for shop_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.send_lon
     *
     * @return the value of shop_info.send_lon
     *
     * @mbggenerated
     */
    public String getSendLon() {
        return sendLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.send_lon
     *
     * @param sendLon the value for shop_info.send_lon
     *
     * @mbggenerated
     */
    public void setSendLon(String sendLon) {
        this.sendLon = sendLon == null ? null : sendLon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.send_lat
     *
     * @return the value of shop_info.send_lat
     *
     * @mbggenerated
     */
    public String getSendLat() {
        return sendLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.send_lat
     *
     * @param sendLat the value for shop_info.send_lat
     *
     * @mbggenerated
     */
    public void setSendLat(String sendLat) {
        this.sendLat = sendLat == null ? null : sendLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.send_address
     *
     * @return the value of shop_info.send_address
     *
     * @mbggenerated
     */
    public String getSendAddress() {
        return sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.send_address
     *
     * @param sendAddress the value for shop_info.send_address
     *
     * @mbggenerated
     */
    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress == null ? null : sendAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.send_country
     *
     * @return the value of shop_info.send_country
     *
     * @mbggenerated
     */
    public String getSendCountry() {
        return sendCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.send_country
     *
     * @param sendCountry the value for shop_info.send_country
     *
     * @mbggenerated
     */
    public void setSendCountry(String sendCountry) {
        this.sendCountry = sendCountry == null ? null : sendCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.send_province_code
     *
     * @return the value of shop_info.send_province_code
     *
     * @mbggenerated
     */
    public String getSendProvinceCode() {
        return sendProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.send_province_code
     *
     * @param sendProvinceCode the value for shop_info.send_province_code
     *
     * @mbggenerated
     */
    public void setSendProvinceCode(String sendProvinceCode) {
        this.sendProvinceCode = sendProvinceCode == null ? null : sendProvinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.send_city_code
     *
     * @return the value of shop_info.send_city_code
     *
     * @mbggenerated
     */
    public String getSendCityCode() {
        return sendCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.send_city_code
     *
     * @param sendCityCode the value for shop_info.send_city_code
     *
     * @mbggenerated
     */
    public void setSendCityCode(String sendCityCode) {
        this.sendCityCode = sendCityCode == null ? null : sendCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_type
     *
     * @return the value of shop_info.shop_type
     *
     * @mbggenerated
     */
    public Byte getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_type
     *
     * @param shopType the value for shop_info.shop_type
     *
     * @mbggenerated
     */
    public void setShopType(Byte shopType) {
        this.shopType = shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_name
     *
     * @return the value of shop_info.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_name
     *
     * @param shopName the value for shop_info.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_lon
     *
     * @return the value of shop_info.shop_lon
     *
     * @mbggenerated
     */
    public String getShopLon() {
        return shopLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_lon
     *
     * @param shopLon the value for shop_info.shop_lon
     *
     * @mbggenerated
     */
    public void setShopLon(String shopLon) {
        this.shopLon = shopLon == null ? null : shopLon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_lat
     *
     * @return the value of shop_info.shop_lat
     *
     * @mbggenerated
     */
    public String getShopLat() {
        return shopLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_lat
     *
     * @param shopLat the value for shop_info.shop_lat
     *
     * @mbggenerated
     */
    public void setShopLat(String shopLat) {
        this.shopLat = shopLat == null ? null : shopLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_address
     *
     * @return the value of shop_info.shop_address
     *
     * @mbggenerated
     */
    public String getShopAddress() {
        return shopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_address
     *
     * @param shopAddress the value for shop_info.shop_address
     *
     * @mbggenerated
     */
    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress == null ? null : shopAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_country
     *
     * @return the value of shop_info.shop_country
     *
     * @mbggenerated
     */
    public String getShopCountry() {
        return shopCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_country
     *
     * @param shopCountry the value for shop_info.shop_country
     *
     * @mbggenerated
     */
    public void setShopCountry(String shopCountry) {
        this.shopCountry = shopCountry == null ? null : shopCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_province_code
     *
     * @return the value of shop_info.shop_province_code
     *
     * @mbggenerated
     */
    public String getShopProvinceCode() {
        return shopProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_province_code
     *
     * @param shopProvinceCode the value for shop_info.shop_province_code
     *
     * @mbggenerated
     */
    public void setShopProvinceCode(String shopProvinceCode) {
        this.shopProvinceCode = shopProvinceCode == null ? null : shopProvinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_city_code
     *
     * @return the value of shop_info.shop_city_code
     *
     * @mbggenerated
     */
    public String getShopCityCode() {
        return shopCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_city_code
     *
     * @param shopCityCode the value for shop_info.shop_city_code
     *
     * @mbggenerated
     */
    public void setShopCityCode(String shopCityCode) {
        this.shopCityCode = shopCityCode == null ? null : shopCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.idcard_front
     *
     * @return the value of shop_info.idcard_front
     *
     * @mbggenerated
     */
    public String getIdcardFront() {
        return idcardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.idcard_front
     *
     * @param idcardFront the value for shop_info.idcard_front
     *
     * @mbggenerated
     */
    public void setIdcardFront(String idcardFront) {
        this.idcardFront = idcardFront == null ? null : idcardFront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.idcard_back
     *
     * @return the value of shop_info.idcard_back
     *
     * @mbggenerated
     */
    public String getIdcardBack() {
        return idcardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.idcard_back
     *
     * @param idcardBack the value for shop_info.idcard_back
     *
     * @mbggenerated
     */
    public void setIdcardBack(String idcardBack) {
        this.idcardBack = idcardBack == null ? null : idcardBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.real_name
     *
     * @return the value of shop_info.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.real_name
     *
     * @param realName the value for shop_info.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.idcard
     *
     * @return the value of shop_info.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.idcard
     *
     * @param idcard the value for shop_info.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.vaild_type
     *
     * @return the value of shop_info.vaild_type
     *
     * @mbggenerated
     */
    public Byte getVaildType() {
        return vaildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.vaild_type
     *
     * @param vaildType the value for shop_info.vaild_type
     *
     * @mbggenerated
     */
    public void setVaildType(Byte vaildType) {
        this.vaildType = vaildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.vaild_start_at
     *
     * @return the value of shop_info.vaild_start_at
     *
     * @mbggenerated
     */
    public Date getVaildStartAt() {
        return vaildStartAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.vaild_start_at
     *
     * @param vaildStartAt the value for shop_info.vaild_start_at
     *
     * @mbggenerated
     */
    public void setVaildStartAt(Date vaildStartAt) {
        this.vaildStartAt = vaildStartAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.vaild_end_at
     *
     * @return the value of shop_info.vaild_end_at
     *
     * @mbggenerated
     */
    public Date getVaildEndAt() {
        return vaildEndAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.vaild_end_at
     *
     * @param vaildEndAt the value for shop_info.vaild_end_at
     *
     * @mbggenerated
     */
    public void setVaildEndAt(Date vaildEndAt) {
        this.vaildEndAt = vaildEndAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.invite_code
     *
     * @return the value of shop_info.invite_code
     *
     * @mbggenerated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.invite_code
     *
     * @param inviteCode the value for shop_info.invite_code
     *
     * @mbggenerated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.vip
     *
     * @return the value of shop_info.vip
     *
     * @mbggenerated
     */
    public Byte getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.vip
     *
     * @param vip the value for shop_info.vip
     *
     * @mbggenerated
     */
    public void setVip(Byte vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.level
     *
     * @return the value of shop_info.level
     *
     * @mbggenerated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.level
     *
     * @param level the value for shop_info.level
     *
     * @mbggenerated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.stock_num
     *
     * @return the value of shop_info.stock_num
     *
     * @mbggenerated
     */
    public Integer getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.stock_num
     *
     * @param stockNum the value for shop_info.stock_num
     *
     * @mbggenerated
     */
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.create_time2
     *
     * @return the value of shop_info.create_time2
     *
     * @mbggenerated
     */
    public Date getCreateTime2() {
        return createTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.create_time2
     *
     * @param createTime2 the value for shop_info.create_time2
     *
     * @mbggenerated
     */
    public void setCreateTime2(Date createTime2) {
        this.createTime2 = createTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.modify_time
     *
     * @return the value of shop_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.modify_time
     *
     * @param modifyTime the value for shop_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.operator_id
     *
     * @return the value of shop_info.operator_id
     *
     * @mbggenerated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.operator_id
     *
     * @param operatorId the value for shop_info.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.slogan
     *
     * @return the value of shop_info.slogan
     *
     * @mbggenerated
     */
    public String getSlogan() {
        return slogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.slogan
     *
     * @param slogan the value for shop_info.slogan
     *
     * @mbggenerated
     */
    public void setSlogan(String slogan) {
        this.slogan = slogan == null ? null : slogan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", mobile=").append(mobile);
        sb.append(", status=").append(status);
        sb.append(", sendLon=").append(sendLon);
        sb.append(", sendLat=").append(sendLat);
        sb.append(", sendAddress=").append(sendAddress);
        sb.append(", sendCountry=").append(sendCountry);
        sb.append(", sendProvinceCode=").append(sendProvinceCode);
        sb.append(", sendCityCode=").append(sendCityCode);
        sb.append(", shopType=").append(shopType);
        sb.append(", shopName=").append(shopName);
        sb.append(", shopLon=").append(shopLon);
        sb.append(", shopLat=").append(shopLat);
        sb.append(", shopAddress=").append(shopAddress);
        sb.append(", shopCountry=").append(shopCountry);
        sb.append(", shopProvinceCode=").append(shopProvinceCode);
        sb.append(", shopCityCode=").append(shopCityCode);
        sb.append(", idcardFront=").append(idcardFront);
        sb.append(", idcardBack=").append(idcardBack);
        sb.append(", realName=").append(realName);
        sb.append(", idcard=").append(idcard);
        sb.append(", vaildType=").append(vaildType);
        sb.append(", vaildStartAt=").append(vaildStartAt);
        sb.append(", vaildEndAt=").append(vaildEndAt);
        sb.append(", inviteCode=").append(inviteCode);
        sb.append(", vip=").append(vip);
        sb.append(", level=").append(level);
        sb.append(", stockNum=").append(stockNum);
        sb.append(", createTime2=").append(createTime2);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", slogan=").append(slogan);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}