package com.ly.mt.activity.server.order.mapper;

import com.ly.mt.core.common.entity.hd.HdShopAttOrder;
import com.ly.mt.core.common.entity.hd.vo.HdShopAttDetailVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

@Mapper
public interface HdShopAttOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_order
     *
     * @mbggenerated
     */
    int insert(HdShopAttOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_order
     *
     * @mbggenerated
     */
    int insertSelective(HdShopAttOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_order
     *
     * @mbggenerated
     */
    HdShopAttOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HdShopAttOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HdShopAttOrder record);


    /**
     * 条件查询
     * map的key表名，value为查询的值
     * @param condition
     * @return
     */
    List<Map<String,Object>> searchConditions(@Param("condition") Map<String,Object> condition);

    /**
     *
     * @param conditions
     * @return
     */
    List<HdShopAttOrder> pageConditions(@Param("hdShopAttDetailVo") HdShopAttDetailVo vo, @Param("conditions")Map<String,Object> conditions);

    /**
     * 商家修改订单状态
     * 带取货码时候如果对不上则返回0，认为取货码不对
     * @param orderId 单号
     * @param orderStatus 订单状态
     * @param getProuctCode 取货码
     * @return
     */
    Integer shopChangeStatus(@Param("orderId") String orderId, @Param("orderStatus") String orderStatus,@Param("getProuctCode") String getProuctCode);

    /**
     * 买家查询订单
     * @param attUserId
     * @param attDetailId
     * @return
     */
    @Select("select * from hd_shop_att_order where user_id = #{attUserId} and shop_att_detail_id = #{attDetailId}")
    List<HdShopAttOrder> findByUserIdAttDetailId(@Param("attUserId") Long attUserId,@Param("attDetailId") Long attDetailId);

    /**
     * 查询用户手机号码
     * @param userId
     * @return
     */
    @Select("select phone from hd_activity_user where id = #{id}")
    String findBuyerPhoneBuyUserId(@Param("id") Long userId);

    /**
     * 查询订单根据单号
     * @param orderId
     * @return
     */
    @Select("select * from hd_shop_att_order where order_id = #{orderId}")
    HdShopAttOrder findByOrderId(@Param("orderId") String orderId);
}