package com.ly.mt.core.base.entity.hd;

import java.io.Serializable;
import java.util.Date;
/** @deprecated */
public class HdOperatorInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_code
     *
     * @mbggenerated
     */
    private String operatorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_ country_id
     *
     * @mbggenerated
     */
    private Long operatorCountryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_province_id
     *
     * @mbggenerated
     */
    private Long operatorProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_city_id
     *
     * @mbggenerated
     */
    private Long operatorCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_name
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_msg
     *
     * @mbggenerated
     */
    private String operatorMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_phone
     *
     * @mbggenerated
     */
    private String operatorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_person
     *
     * @mbggenerated
     */
    private String operatorPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.operator_status
     *
     * @mbggenerated
     */
    private String operatorStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_operator_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hd_operator_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.id
     *
     * @return the value of hd_operator_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.id
     *
     * @param id the value for hd_operator_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_code
     *
     * @return the value of hd_operator_info.operator_code
     *
     * @mbggenerated
     */
    public String getOperatorCode() {
        return operatorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_code
     *
     * @param operatorCode the value for hd_operator_info.operator_code
     *
     * @mbggenerated
     */
    public void setOperatorCode(String operatorCode) {
        this.operatorCode = operatorCode == null ? null : operatorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_ country_id
     *
     * @return the value of hd_operator_info.operator_ country_id
     *
     * @mbggenerated
     */
    public Long getOperatorCountryId() {
        return operatorCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_ country_id
     *
     * @param operatorCountryId the value for hd_operator_info.operator_ country_id
     *
     * @mbggenerated
     */
    public void setOperatorCountryId(Long operatorCountryId) {
        this.operatorCountryId = operatorCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_province_id
     *
     * @return the value of hd_operator_info.operator_province_id
     *
     * @mbggenerated
     */
    public Long getOperatorProvinceId() {
        return operatorProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_province_id
     *
     * @param operatorProvinceId the value for hd_operator_info.operator_province_id
     *
     * @mbggenerated
     */
    public void setOperatorProvinceId(Long operatorProvinceId) {
        this.operatorProvinceId = operatorProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_city_id
     *
     * @return the value of hd_operator_info.operator_city_id
     *
     * @mbggenerated
     */
    public Long getOperatorCityId() {
        return operatorCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_city_id
     *
     * @param operatorCityId the value for hd_operator_info.operator_city_id
     *
     * @mbggenerated
     */
    public void setOperatorCityId(Long operatorCityId) {
        this.operatorCityId = operatorCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_name
     *
     * @return the value of hd_operator_info.operator_name
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_name
     *
     * @param operatorName the value for hd_operator_info.operator_name
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_msg
     *
     * @return the value of hd_operator_info.operator_msg
     *
     * @mbggenerated
     */
    public String getOperatorMsg() {
        return operatorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_msg
     *
     * @param operatorMsg the value for hd_operator_info.operator_msg
     *
     * @mbggenerated
     */
    public void setOperatorMsg(String operatorMsg) {
        this.operatorMsg = operatorMsg == null ? null : operatorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_phone
     *
     * @return the value of hd_operator_info.operator_phone
     *
     * @mbggenerated
     */
    public String getOperatorPhone() {
        return operatorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_phone
     *
     * @param operatorPhone the value for hd_operator_info.operator_phone
     *
     * @mbggenerated
     */
    public void setOperatorPhone(String operatorPhone) {
        this.operatorPhone = operatorPhone == null ? null : operatorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_person
     *
     * @return the value of hd_operator_info.operator_person
     *
     * @mbggenerated
     */
    public String getOperatorPerson() {
        return operatorPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_person
     *
     * @param operatorPerson the value for hd_operator_info.operator_person
     *
     * @mbggenerated
     */
    public void setOperatorPerson(String operatorPerson) {
        this.operatorPerson = operatorPerson == null ? null : operatorPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.operator_status
     *
     * @return the value of hd_operator_info.operator_status
     *
     * @mbggenerated
     */
    public String getOperatorStatus() {
        return operatorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.operator_status
     *
     * @param operatorStatus the value for hd_operator_info.operator_status
     *
     * @mbggenerated
     */
    public void setOperatorStatus(String operatorStatus) {
        this.operatorStatus = operatorStatus == null ? null : operatorStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.create_time
     *
     * @return the value of hd_operator_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.create_time
     *
     * @param createTime the value for hd_operator_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_operator_info.update_time
     *
     * @return the value of hd_operator_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_operator_info.update_time
     *
     * @param updateTime the value for hd_operator_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_operator_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", operatorCode=").append(operatorCode);
        sb.append(", operatorCountryId=").append(operatorCountryId);
        sb.append(", operatorProvinceId=").append(operatorProvinceId);
        sb.append(", operatorCityId=").append(operatorCityId);
        sb.append(", operatorName=").append(operatorName);
        sb.append(", operatorMsg=").append(operatorMsg);
        sb.append(", operatorPhone=").append(operatorPhone);
        sb.append(", operatorPerson=").append(operatorPerson);
        sb.append(", operatorStatus=").append(operatorStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}