package com.ly.mt.core.base.entity.hd;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
/** @deprecated */
public class HdShopAttOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.shop_att_detail_id
     *
     * @mbggenerated
     */
    private Long shopAttDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.shop_id
     *
     * @mbggenerated
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.order_status
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.shipping_address
     *
     * @mbggenerated
     */
    private String shippingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.user_address_id
     *
     * @mbggenerated
     */
    private Long userAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.get_goods_code
     *
     * @mbggenerated
     */
    private String getGoodsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order.order_type
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hd_shop_att_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.id
     *
     * @return the value of hd_shop_att_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.id
     *
     * @param id the value for hd_shop_att_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.order_id
     *
     * @return the value of hd_shop_att_order.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.order_id
     *
     * @param orderId the value for hd_shop_att_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.user_id
     *
     * @return the value of hd_shop_att_order.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.user_id
     *
     * @param userId the value for hd_shop_att_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.shop_att_detail_id
     *
     * @return the value of hd_shop_att_order.shop_att_detail_id
     *
     * @mbggenerated
     */
    public Long getShopAttDetailId() {
        return shopAttDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.shop_att_detail_id
     *
     * @param shopAttDetailId the value for hd_shop_att_order.shop_att_detail_id
     *
     * @mbggenerated
     */
    public void setShopAttDetailId(Long shopAttDetailId) {
        this.shopAttDetailId = shopAttDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.shop_id
     *
     * @return the value of hd_shop_att_order.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.shop_id
     *
     * @param shopId the value for hd_shop_att_order.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.total_price
     *
     * @return the value of hd_shop_att_order.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.total_price
     *
     * @param totalPrice the value for hd_shop_att_order.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.order_status
     *
     * @return the value of hd_shop_att_order.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.order_status
     *
     * @param orderStatus the value for hd_shop_att_order.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.shipping_address
     *
     * @return the value of hd_shop_att_order.shipping_address
     *
     * @mbggenerated
     */
    public String getShippingAddress() {
        return shippingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.shipping_address
     *
     * @param shippingAddress the value for hd_shop_att_order.shipping_address
     *
     * @mbggenerated
     */
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress == null ? null : shippingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.user_address_id
     *
     * @return the value of hd_shop_att_order.user_address_id
     *
     * @mbggenerated
     */
    public Long getUserAddressId() {
        return userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.user_address_id
     *
     * @param userAddressId the value for hd_shop_att_order.user_address_id
     *
     * @mbggenerated
     */
    public void setUserAddressId(Long userAddressId) {
        this.userAddressId = userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.get_goods_code
     *
     * @return the value of hd_shop_att_order.get_goods_code
     *
     * @mbggenerated
     */
    public String getGetGoodsCode() {
        return getGoodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.get_goods_code
     *
     * @param getGoodsCode the value for hd_shop_att_order.get_goods_code
     *
     * @mbggenerated
     */
    public void setGetGoodsCode(String getGoodsCode) {
        this.getGoodsCode = getGoodsCode == null ? null : getGoodsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.create_time
     *
     * @return the value of hd_shop_att_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.create_time
     *
     * @param createTime the value for hd_shop_att_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.update_time
     *
     * @return the value of hd_shop_att_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.update_time
     *
     * @param updateTime the value for hd_shop_att_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order.order_type
     *
     * @return the value of hd_shop_att_order.order_type
     *
     * @mbggenerated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order.order_type
     *
     * @param orderType the value for hd_shop_att_order.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", userId=").append(userId);
        sb.append(", shopAttDetailId=").append(shopAttDetailId);
        sb.append(", shopId=").append(shopId);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", shippingAddress=").append(shippingAddress);
        sb.append(", userAddressId=").append(userAddressId);
        sb.append(", getGoodsCode=").append(getGoodsCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", orderType=").append(orderType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}