package com.ly.mt.core.base.entity.hd;

import java.io.Serializable;
import java.util.Date;
/** @deprecated */
public class HdShopAttGoodspu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_goods_spu.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_goods_spu.shop_att_detail_id
     *
     * @mbggenerated
     */
    private Long shopAttDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_goods_spu.goods_spu_info_id
     *
     * @mbggenerated
     */
    private Long goodsSpuInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_goods_spu.goods_status
     *
     * @mbggenerated
     */
    private String goodsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_goods_spu.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_goods_spu.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_goods_spu.shop_id
     *
     * @mbggenerated
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_goods_spu.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hd_shop_att_goods_spu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_goods_spu.id
     *
     * @return the value of hd_shop_att_goods_spu.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_goods_spu.id
     *
     * @param id the value for hd_shop_att_goods_spu.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_goods_spu.shop_att_detail_id
     *
     * @return the value of hd_shop_att_goods_spu.shop_att_detail_id
     *
     * @mbggenerated
     */
    public Long getShopAttDetailId() {
        return shopAttDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_goods_spu.shop_att_detail_id
     *
     * @param shopAttDetailId the value for hd_shop_att_goods_spu.shop_att_detail_id
     *
     * @mbggenerated
     */
    public void setShopAttDetailId(Long shopAttDetailId) {
        this.shopAttDetailId = shopAttDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_goods_spu.goods_spu_info_id
     *
     * @return the value of hd_shop_att_goods_spu.goods_spu_info_id
     *
     * @mbggenerated
     */
    public Long getGoodsSpuInfoId() {
        return goodsSpuInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_goods_spu.goods_spu_info_id
     *
     * @param goodsSpuInfoId the value for hd_shop_att_goods_spu.goods_spu_info_id
     *
     * @mbggenerated
     */
    public void setGoodsSpuInfoId(Long goodsSpuInfoId) {
        this.goodsSpuInfoId = goodsSpuInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_goods_spu.goods_status
     *
     * @return the value of hd_shop_att_goods_spu.goods_status
     *
     * @mbggenerated
     */
    public String getGoodsStatus() {
        return goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_goods_spu.goods_status
     *
     * @param goodsStatus the value for hd_shop_att_goods_spu.goods_status
     *
     * @mbggenerated
     */
    public void setGoodsStatus(String goodsStatus) {
        this.goodsStatus = goodsStatus == null ? null : goodsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_goods_spu.create_time
     *
     * @return the value of hd_shop_att_goods_spu.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_goods_spu.create_time
     *
     * @param createTime the value for hd_shop_att_goods_spu.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_goods_spu.update_time
     *
     * @return the value of hd_shop_att_goods_spu.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_goods_spu.update_time
     *
     * @param updateTime the value for hd_shop_att_goods_spu.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_goods_spu.shop_id
     *
     * @return the value of hd_shop_att_goods_spu.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_goods_spu.shop_id
     *
     * @param shopId the value for hd_shop_att_goods_spu.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_goods_spu.activity_id
     *
     * @return the value of hd_shop_att_goods_spu.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_goods_spu.activity_id
     *
     * @param activityId the value for hd_shop_att_goods_spu.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_goods_spu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shopAttDetailId=").append(shopAttDetailId);
        sb.append(", goodsSpuInfoId=").append(goodsSpuInfoId);
        sb.append(", goodsStatus=").append(goodsStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", shopId=").append(shopId);
        sb.append(", activityId=").append(activityId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}