package com.ly.mt.core.base.entity.hd;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
/** @deprecated */
public class HdShopAttOrderDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.shop_att_detail_id
     *
     * @mbggenerated
     */
    private Long shopAttDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.goods_sku_id
     *
     * @mbggenerated
     */
    private Long goodsSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.goods_spu_id
     *
     * @mbggenerated
     */
    private Long goodsSpuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.goods_quantity
     *
     * @mbggenerated
     */
    private Integer goodsQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.goods_price
     *
     * @mbggenerated
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_shop_att_order_detail.uodate_time
     *
     * @mbggenerated
     */
    private Date uodateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hd_shop_att_order_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.id
     *
     * @return the value of hd_shop_att_order_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.id
     *
     * @param id the value for hd_shop_att_order_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.order_id
     *
     * @return the value of hd_shop_att_order_detail.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.order_id
     *
     * @param orderId the value for hd_shop_att_order_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.user_id
     *
     * @return the value of hd_shop_att_order_detail.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.user_id
     *
     * @param userId the value for hd_shop_att_order_detail.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.shop_att_detail_id
     *
     * @return the value of hd_shop_att_order_detail.shop_att_detail_id
     *
     * @mbggenerated
     */
    public Long getShopAttDetailId() {
        return shopAttDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.shop_att_detail_id
     *
     * @param shopAttDetailId the value for hd_shop_att_order_detail.shop_att_detail_id
     *
     * @mbggenerated
     */
    public void setShopAttDetailId(Long shopAttDetailId) {
        this.shopAttDetailId = shopAttDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.goods_sku_id
     *
     * @return the value of hd_shop_att_order_detail.goods_sku_id
     *
     * @mbggenerated
     */
    public Long getGoodsSkuId() {
        return goodsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.goods_sku_id
     *
     * @param goodsSkuId the value for hd_shop_att_order_detail.goods_sku_id
     *
     * @mbggenerated
     */
    public void setGoodsSkuId(Long goodsSkuId) {
        this.goodsSkuId = goodsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.goods_spu_id
     *
     * @return the value of hd_shop_att_order_detail.goods_spu_id
     *
     * @mbggenerated
     */
    public Long getGoodsSpuId() {
        return goodsSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.goods_spu_id
     *
     * @param goodsSpuId the value for hd_shop_att_order_detail.goods_spu_id
     *
     * @mbggenerated
     */
    public void setGoodsSpuId(Long goodsSpuId) {
        this.goodsSpuId = goodsSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.goods_quantity
     *
     * @return the value of hd_shop_att_order_detail.goods_quantity
     *
     * @mbggenerated
     */
    public Integer getGoodsQuantity() {
        return goodsQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.goods_quantity
     *
     * @param goodsQuantity the value for hd_shop_att_order_detail.goods_quantity
     *
     * @mbggenerated
     */
    public void setGoodsQuantity(Integer goodsQuantity) {
        this.goodsQuantity = goodsQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.goods_price
     *
     * @return the value of hd_shop_att_order_detail.goods_price
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.goods_price
     *
     * @param goodsPrice the value for hd_shop_att_order_detail.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.create_time
     *
     * @return the value of hd_shop_att_order_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.create_time
     *
     * @param createTime the value for hd_shop_att_order_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_shop_att_order_detail.uodate_time
     *
     * @return the value of hd_shop_att_order_detail.uodate_time
     *
     * @mbggenerated
     */
    public Date getUodateTime() {
        return uodateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_shop_att_order_detail.uodate_time
     *
     * @param uodateTime the value for hd_shop_att_order_detail.uodate_time
     *
     * @mbggenerated
     */
    public void setUodateTime(Date uodateTime) {
        this.uodateTime = uodateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_shop_att_order_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", userId=").append(userId);
        sb.append(", shopAttDetailId=").append(shopAttDetailId);
        sb.append(", goodsSkuId=").append(goodsSkuId);
        sb.append(", goodsSpuId=").append(goodsSpuId);
        sb.append(", goodsQuantity=").append(goodsQuantity);
        sb.append(", goodsPrice=").append(goodsPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", uodateTime=").append(uodateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}