package com.ly.mt.core.base.entity.hd;

import java.io.Serializable;
import java.util.Date;
/** @deprecated */
public class HdUserInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_open_id
     *
     * @mbggenerated
     */
    private String wxOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_open_id
     *
     * @mbggenerated
     */
    private String qqOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.district_code
     *
     * @mbggenerated
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.valid_status
     *
     * @mbggenerated
     */
    private Integer validStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_status
     *
     * @mbggenerated
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shop_id
     *
     * @mbggenerated
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.auditor
     *
     * @mbggenerated
     */
    private Long auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.audit_remark
     *
     * @mbggenerated
     */
    private String auditRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.quick_type
     *
     * @mbggenerated
     */
    private Integer quickType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_pic_src
     *
     * @mbggenerated
     */
    private String avatarPicSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notice_config
     *
     * @mbggenerated
     */
    private String noticeConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_open_id
     *
     * @return the value of user.wx_open_id
     *
     * @mbggenerated
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_open_id
     *
     * @param wxOpenId the value for user.wx_open_id
     *
     * @mbggenerated
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_open_id
     *
     * @return the value of user.qq_open_id
     *
     * @mbggenerated
     */
    public String getQqOpenId() {
        return qqOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_open_id
     *
     * @param qqOpenId the value for user.qq_open_id
     *
     * @mbggenerated
     */
    public void setQqOpenId(String qqOpenId) {
        this.qqOpenId = qqOpenId == null ? null : qqOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_name
     *
     * @return the value of user.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_name
     *
     * @param loginName the value for user.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_card
     *
     * @return the value of user.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_card
     *
     * @param idCard the value for user.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province_code
     *
     * @return the value of user.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province_code
     *
     * @param provinceCode the value for user.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city_code
     *
     * @return the value of user.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city_code
     *
     * @param cityCode the value for user.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.district_code
     *
     * @return the value of user.district_code
     *
     * @mbggenerated
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.district_code
     *
     * @param districtCode the value for user.district_code
     *
     * @mbggenerated
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.valid_status
     *
     * @return the value of user.valid_status
     *
     * @mbggenerated
     */
    public Integer getValidStatus() {
        return validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.valid_status
     *
     * @param validStatus the value for user.valid_status
     *
     * @mbggenerated
     */
    public void setValidStatus(Integer validStatus) {
        this.validStatus = validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_status
     *
     * @return the value of user.user_status
     *
     * @mbggenerated
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_status
     *
     * @param userStatus the value for user.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shop_id
     *
     * @return the value of user.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shop_id
     *
     * @param shopId the value for user.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.auditor
     *
     * @return the value of user.auditor
     *
     * @mbggenerated
     */
    public Long getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.auditor
     *
     * @param auditor the value for user.auditor
     *
     * @mbggenerated
     */
    public void setAuditor(Long auditor) {
        this.auditor = auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.audit_remark
     *
     * @return the value of user.audit_remark
     *
     * @mbggenerated
     */
    public String getAuditRemark() {
        return auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.audit_remark
     *
     * @param auditRemark the value for user.audit_remark
     *
     * @mbggenerated
     */
    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark == null ? null : auditRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.quick_type
     *
     * @return the value of user.quick_type
     *
     * @mbggenerated
     */
    public Integer getQuickType() {
        return quickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.quick_type
     *
     * @param quickType the value for user.quick_type
     *
     * @mbggenerated
     */
    public void setQuickType(Integer quickType) {
        this.quickType = quickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_pic_src
     *
     * @return the value of user.avatar_pic_src
     *
     * @mbggenerated
     */
    public String getAvatarPicSrc() {
        return avatarPicSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_pic_src
     *
     * @param avatarPicSrc the value for user.avatar_pic_src
     *
     * @mbggenerated
     */
    public void setAvatarPicSrc(String avatarPicSrc) {
        this.avatarPicSrc = avatarPicSrc == null ? null : avatarPicSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notice_config
     *
     * @return the value of user.notice_config
     *
     * @mbggenerated
     */
    public String getNoticeConfig() {
        return noticeConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notice_config
     *
     * @param noticeConfig the value for user.notice_config
     *
     * @mbggenerated
     */
    public void setNoticeConfig(String noticeConfig) {
        this.noticeConfig = noticeConfig == null ? null : noticeConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", wxOpenId=").append(wxOpenId);
        sb.append(", qqOpenId=").append(qqOpenId);
        sb.append(", loginName=").append(loginName);
        sb.append(", password=").append(password);
        sb.append(", idCard=").append(idCard);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", provinceCode=").append(provinceCode);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", districtCode=").append(districtCode);
        sb.append(", userType=").append(userType);
        sb.append(", nickName=").append(nickName);
        sb.append(", validStatus=").append(validStatus);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", shopId=").append(shopId);
        sb.append(", auditor=").append(auditor);
        sb.append(", auditRemark=").append(auditRemark);
        sb.append(", quickType=").append(quickType);
        sb.append(", avatarPicSrc=").append(avatarPicSrc);
        sb.append(", noticeConfig=").append(noticeConfig);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }


    public HdUserInfo() {
    }

    public HdUserInfo(String mobile, Integer sex) {
        this.mobile = mobile;
        this.sex = sex;
    }
}