package com.ly.mt.activity.server.shop.mapper;

import com.ly.mt.core.common.entity.hd.HdOperatorInfo;
import com.ly.mt.core.common.entity.hd.dto.HdoperatorDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface HdOperatorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_operator_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_operator_info
     *
     * @mbggenerated
     */
    int insert(HdOperatorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_operator_info
     *
     * @mbggenerated
     */
    int insertSelective(HdOperatorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_operator_info
     *
     * @mbggenerated
     */
    HdOperatorInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_operator_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HdOperatorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_operator_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HdOperatorInfo record);

    @Select("select * from hd_operator_info")
    List<HdoperatorDto> findOperatorAll();
}