package com.ly.mt.activity.server.shop.mapper;

import com.ly.mt.core.common.entity.hd.HdShopInfo;
import com.ly.mt.core.common.entity.hd.vo.HdShopInfoDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface HdShopInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    int insert(HdShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    int insertSelective(HdShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    HdShopInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HdShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(HdShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HdShopInfo record);

    /**
     * 根据代理商id查询门店信息
     * @param operatorId
     * @return
     */
    @Select("select id,shop_name,shop_address,mobile from shop_info where operator_id = #{operatorId}")
    List<HdShopInfoDto> findByOperatorId(@Param("operatorId") Long operatorId);
}