package com.ly.mt.activity.server.attmeg.mapper;

import com.ly.mt.core.common.entity.hd.HdActivityInfo;

public interface HdActivityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_info
     *
     * @mbggenerated
     */
    int insert(HdActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_info
     *
     * @mbggenerated
     */
    int insertSelective(HdActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_info
     *
     * @mbggenerated
     */
    HdActivityInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HdActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HdActivityInfo record);
}